export const courses = [
    {
        id: 1,
        title: "Maîtriser Next.js 15 & React 19",
        description: "Le guide complet pour créer des applications web modernes avec les dernières technologies.",
        image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=3270&auto=format&fit=crop",
        level: "Intermédiaire",
        category: "Développement Web",
        price: 0,
        rating: 4.8,
        lessonsCount: 42,
        duration: "12h",
        slug: "nextjs-15-react-19"
    },
    {
        id: 2,
        title: "DevOps : De zéro à héros",
        description: "Apprenez Docker, Kubernetes, CI/CD et l'infrastructure as code.",
        image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?q=80&w=3288&auto=format&fit=crop",
        level: "Avancé",
        category: "DevOps",
        price: 0,
        rating: 4.9,
        lessonsCount: 65,
        duration: "20h",
        slug: "devops-zero-hero"
    },
    {
        id: 3,
        title: "Introduction à l'IA et au Machine Learning",
        description: "Comprendre les bases de l'intelligence artificielle et créer ses premiers modèles.",
        image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=3132&auto=format&fit=crop",
        level: "Débutant",
        category: "Intelligence Artificielle",
        price: 0,
        rating: 4.7,
        lessonsCount: 24,
        duration: "8h",
        slug: "intro-ia-ml"
    },
    {
        id: 4,
        title: "Framer Motion & Animations Avancées",
        description: "Donnez vie à vos interfaces React avec des animations fluides et complexes.",
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=3270&auto=format&fit=crop",
        level: "Intermédiaire",
        category: "Design & UX",
        price: 0,
        rating: 4.9,
        lessonsCount: 18,
        duration: "6h",
        slug: "framer-motion-animations"
    },
    {
        id: 5,
        title: "TypeScript : Du débutant à l'expert",
        description: "Maîtrisez TypeScript pour écrire du code JavaScript robuste et maintenable.",
        image: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=3270&auto=format&fit=crop",
        level: "Débutant",
        category: "Développement Web",
        price: 0,
        rating: 4.8,
        lessonsCount: 35,
        duration: "10h",
        slug: "typescript-expert"
    },
    {
        id: 6,
        title: "Python pour la Data Science",
        description: "Analysez des données avec Pandas, NumPy et créez des visualisations percutantes.",
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=3270&auto=format&fit=crop",
        level: "Intermédiaire",
        category: "Data Science",
        price: 0,
        rating: 4.7,
        lessonsCount: 48,
        duration: "15h",
        slug: "python-data-science"
    },
    {
        id: 7,
        title: "Cybersécurité : Les fondamentaux",
        description: "Apprenez à sécuriser vos applications et à détecter les vulnérabilités.",
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=3270&auto=format&fit=crop",
        level: "Intermédiaire",
        category: "Cybersécurité",
        price: 0,
        rating: 4.9,
        lessonsCount: 52,
        duration: "18h",
        slug: "cybersecurity-fundamentals"
    },
    {
        id: 8,
        title: "React Native : Applications mobiles",
        description: "Créez des applications iOS et Android avec React Native et Expo.",
        image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=3270&auto=format&fit=crop",
        level: "Intermédiaire",
        category: "Développement Mobile",
        price: 0,
        rating: 4.6,
        lessonsCount: 38,
        duration: "14h",
        slug: "react-native-mobile"
    }
]
